[phpproject]
# PHP extensions required for your Laravel app
extensions = ["gd", "mbstring", "pdo_pgsql", "openssl", "tokenizer", "ctype", "json", "fileinfo", "bcmath", "xml"]

# PHP version
version = "8.4"

# Composer install with platform requirements enforced
install = "composer install --optimize-autoloader --no-interaction --no-scripts"

# Optional: run artisan commands before starting the app
build = """
php artisan key:generate
php artisan migrate --force
php artisan config:cache
php artisan route:cache
php artisan view:cache
"""

# Start command for Laravel
start = "php artisan serve --host=0.0.0.0 --port=${PORT}"
